# Generated by Django 5.0.2 on 2024-04-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0004_rename_user_auth_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auth_user',
            new_name='User',
        ),
    ]
