# Generated by Django 5.0.2 on 2024-04-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0005_rename_auth_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
