# Generated by Django 5.0.2 on 2024-04-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0007_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userstbl',
        ),
    ]
