# Generated by Django 5.0.2 on 2024-04-17 14:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0010_userstbl_is_active_userstbl_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userstbl',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
