# Generated by Django 5.0.2 on 2024-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0012_alter_userstbl_options_alter_userstbl_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstbl',
            name='mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
