# Generated by Django 5.0.2 on 2024-04-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0013_userstbl_mail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstbl',
            options={},
        ),
        migrations.RemoveField(
            model_name='userstbl',
            name='password',
        ),
    ]
