# Generated by Django 5.0.2 on 2024-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0014_alter_userstbl_options_remove_userstbl_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstbl',
            name='password',
            field=models.CharField(default='S', max_length=120),
            preserve_default=False,
        ),
    ]
