# Generated by Django 5.0.2 on 2024-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0015_userstbl_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstbl',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
