# Generated by Django 5.0.2 on 2024-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0016_alter_userstbl_options_alter_userstbl_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertable_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
