# Generated by Django 5.0.2 on 2024-04-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0017_mail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_status',
            name='token',
            field=models.CharField(default='eer', max_length=100),
            preserve_default=False,
        ),
    ]
