# Generated by Django 5.0.2 on 2024-04-20 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0019_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('job_category', models.IntegerField()),
                ('state', models.IntegerField(max_length=100)),
                ('city', models.IntegerField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('job_summary', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=100)),
                ('vacancies', models.CharField(max_length=100)),
                ('job_closingdate', models.DateField()),
                ('comp_dtls', models.CharField(max_length=500)),
                ('comp_address', models.CharField(max_length=500)),
                ('comp_logo', models.ImageField(upload_to='company_logo/')),
                ('job_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
            ],
        ),
    ]
