# Generated by Django 5.0.2 on 2024-04-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0020_job_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_post',
            new_name='Addjobs',
        ),
    ]
