# Generated by Django 5.0.2 on 2024-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0023_alter_addjobs_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobs',
            name='compname',
            field=models.CharField(default='ww', max_length=500),
            preserve_default=False,
        ),
    ]
