# Generated by Django 5.0.2 on 2024-04-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0024_addjobs_compname'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobs',
            name='postedby',
            field=models.CharField(default='sruthi', max_length=100),
            preserve_default=False,
        ),
    ]
