# Generated by Django 5.0.2 on 2024-04-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0026_jobapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='application_status',
            field=models.BooleanField(default=True),
        ),
    ]
