# Generated by Django 5.0.2 on 2024-04-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0030_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonial',
            new_name='testimonialtbl',
        ),
    ]
