# Generated by Django 5.0.2 on 2024-04-25 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0031_rename_testimonial_testimonialtbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=1500)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
            ],
        ),
    ]
