# Generated by Django 5.0.2 on 2024-04-25 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0032_contacttbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('about', models.CharField(max_length=2500)),
                ('education', models.CharField(max_length=2500)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('job_responsibilities', models.CharField(max_length=2000)),
                ('job_experience', models.CharField(max_length=1000)),
                ('postedby', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
            ],
        ),
    ]
