# Generated by Django 5.0.2 on 2024-04-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPAPP', '0033_profile_datatable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_datatable',
            new_name='Profile_table',
        ),
    ]
